### ISSUE TITLE
Function folding that have comments inside the body

### ISSUE THREAD

**Issue by lamalab** [robballou/atom-fold-functions#16]
Hi,
I've noticed that the autofolding doesn't work very well if there are one or more comments inside the code  block to fold. 
Here is an example:
![image](https://cloud.githubusercontent.com/assets/15817529/15264808/e463e702-1977-11e6-9c6c-1ec0befa4436.png)
The function end with the last bracket, but is autofolded before, at the beginning of the commet.

Thanks ENx

**Comment by robballou** [comment]
With the comments outside of the folding, that breaks Atom's folding (and most editors, I think). To test it out, just try folding that block with the default folding functionality and I don't think it will behave correctly. To "fix" the line comments should be just in front of the code is commenting, not at the start of the line.
