### ISSUE TITLE
Auto folding doesn't work in redux with propTypes that have a shape.

### ISSUE THREAD

**Issue by DaemonCahill** [robballou/atom-fold-functions#17]
Great plugin! Currently using redux and if you have a component with a complex shape as a propType all of the class functions will not fold on load. The propType shape does fold, however.

![screen shot 2016-06-14 at 11 16 20 am](https://cloud.githubusercontent.com/assets/438181/16048301/8ab02e1a-3221-11e6-9b44-f1ec10396694.png)

**Comment by robballou** [comment]
Currently, this package is used to fold functions only. The code example here does not have contain a function scope (most likely, anyway!). If this isn't correct, let me know. Thanks
