### ISSUE TITLE
new feature about autofold

### ISSUE THREAD

**Issue by SimplyY** [robballou/atom-fold-functions#2]
will you have the new feature just like fold-comments
![image](https://cloud.githubusercontent.com/assets/8455579/9151043/2c91e31c-3e27-11e5-88e6-dcebabea2611.png)

**Comment by SimplyY** [comment]
if it has the feature, i think it will be amazing

**Comment by robballou** [comment]
Oh sweet! I tried figuring that out and will have to check out how it's done.

**Comment by robballou** [comment]
Added this, almost verbatim from fold-comments. Thank you for catching that they had added this!

Version 0.3 is now available with this functionality.
