### ISSUE TITLE
Fold in Arrays seems to be buggy

### ISSUE THREAD

**Issue by udayms** [robballou/atom-fold-functions#21]
If I have an array like this -

"labels": [{
		"text": "power/lo",
		"color": "#fad733"
	}, {
		"text": "power/hi",
		"color": "#7266ba"
	}, {
		"text": "power/med",
		"color": "#27c24c"
	}, {
		"text": "power/none",
		"color": "#f05050"
	}]

as part of a larger json structure.. the fold gets a bit buggy. Attempting to fold the labels children only folds one child at a time. Is there any configuration I need to set to get this working properly?

**Comment by robballou** [comment]
Is this while using Atom Fold Functions? https://atom.io/packages/fold-functions

The package is intended to fold functions based on their scope definitions. For JSON, this shouldn't really fold anything (as there are no functions). The default folding behavior is [part of Core atom](https://github.com/atom/atom) but you might need to open a ticket with the JSON language package.
