### ISSUE TITLE
There's no shortcut to toggle fold functions

### ISSUE THREAD

**Issue by Zeioth** [robballou/atom-fold-functions#4]
I would suggest to add a shortcut by default like alt-*

**Comment by robballou** [comment]
Currently, I've left that to up to individuals to configure but could add one if there's a good suggestion for what to use. As an example, you can add this to your keymap file:

``` cson
'atom-text-editor':
  'ctrl-f': 'fold-functions:fold'
```

**Comment by mileung** [comment]
Is there a way to toggle fold-functions:fold and fold-functions:unfold with the same shortcut?

**Comment by robballou** [comment]
@MiLeung Yes, you can set a shortcut for `fold-functions:toggle`
