### ISSUE TITLE
Does not work with es6 code - classes and arrow functions

### ISSUE THREAD

**Issue by forivall** [robballou/atom-fold-functions#5]
With class syntax, something like the class example from https://github.com/lukehoban/es6features
does not get folded when using the command.

Test case: https://gist.github.com/forivall/31d8ff40861245cf5d14

---

Edit: this was the original case, but it works fine.

```
export function foo() {
  bar();
  baz();
}
```

**Comment by robballou** [comment]
Looks like you were affected by changes from #3. The autofolding functionality was changed to not fold short files ([you can configure it](https://github.com/robballou/atom-fold-functions/blob/master/README.md#autofolding)) _but_ I realized that the folding wouldn't work on short files even if you explicitly ran fold later... so I've added a fix for that. Give it a shot and let me know if that fixes it.

**Comment by forivall** [comment]
My bad, I guess that was a bad example. I was trying to create a minimal use case, but I forgot about that feature. I've updated the original with a better example.
